name: timer
channels: 
  - conda-forge
dependencies:
  - python=3.11.4
  - IPython=8.14.0
  - ipykernel=6.23.3
  - ipywidgets=8.0
  - pandas=2.0.2
  - tqdm=4.65.0
  - requests=2.31.0
  - time=1.8
  - configparser=5.3