name: Testing Protocol Timer

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    
jobs:
  protocol-timer-test:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: docker pull pranavmishra90/facsimilab-main:latest

      - name: Save Docker image to cache
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: |
          docker save pranavmishra90/facsimilab-main:latest > /tmp/.docker-cache/image.tar

      - name: PWD
        run: pwd

      - name: Workspace variable
        run: echo "$GITHUB_WORKSPACE"
      
      - name: Run the FFPE Protocol with papermill
        run: |
            docker run --rm --user root -v $GITHUB_WORKSPACE:/home/coder/work pranavmishra90/facsimilab-main:latest cd /home/coder/work && /opt/conda/bin/papermill /home/coder/work/test/test.ipynb /home/coder/work/test-output.ipynb