name: Testing Protocol Timer

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    
jobs:
  protocol-timer-test:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: docker pull pranavmishra90/facsimilab-main:latest

      - name: Pass github secrets in as environment variables
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      
      - run: |
            echo 'Value of TEST_WEBHOOK: $TEST_WEBHOOK'

      - name: Workspace variable
        run: echo "$GITHUB_WORKSPACE"
      
      - name: Run the FFPE Protocol with papermill
        run: |
            docker run --rm --user root -v $GITHUB_WORKSPACE:/home/coder/work -e MATRIX_WEBHOOK=$MATRIX_WEBHOOK -e TEST_WEBHOOK=$TEST_WEBHOOK pranavmishra90/facsimilab-main:latest bash /home/coder/work/test/run-test.sh 

      - name: Write to workflow job summary
        run: |
            header="# Protocol Timer Testing "
            echo "$header" > test/job_summary.md
            echo "Check the [outgoing webhooks](https://webhook.drpranavmishra.com/#!/21adb3bf-8f2b-47d2-9fcc-674451e5e4cd/93753230-4e74-4922-96e1-4097fae1fbba/1)" >> test/job_summary.md
            cat test/job_summary.md >> $GITHUB_STEP_SUMMARY