name: FFPE Protocol

on:
  workflow_dispatch:
    
jobs:
  build-test-and-push:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: PWD
        run: pwd

      - name: Workspace variable
        run: echo "$GITHUB_WORKSPACE"
      
      - name: Run the FFPE Protocol with papermill
        run: |
            docker run --rm -v $GITHUB_WORKSPACE:/home/coder/work pranavmishra90/facsimilab-main:latest /opt/conda/bin/papermill protocols/histology/FFPE.ipynb /tmp/FFPE-run.ipynb